using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System.ComponentModel.DataAnnotations;

namespace OurSolarSystemAPI.Models
{
    public class Barycenter()
{
        [Key]
        public int Id { get; set; } // Auto-generated by SQL 


        [BsonId] // Maps this property to MongoDB's _id field
    [BsonRepresentation(BsonType.ObjectId)] // Ensures compatibility with MongoDB's ObjectId type
    public string MongoId { get; set; } = ObjectId.GenerateNewId().ToString(); // Automatically generates a unique ID

        public required int HorizonId { get; set; }
        public required string Name { get; set; }

        [BsonIgnore] // Prevent circular serialization
        public ICollection<EphemerisBarycenter>? Ephemeris { get; set; }
    }
}
