using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using System.ComponentModel.DataAnnotations;

namespace OurSolarSystemAPI.Models
{
    public class EphemerisPlanet
    {
        [Key]
        public int Id { get; set; } // Auto-generated by SQL 


        [BsonId] // Maps this property to MongoDB's _id field
        [BsonRepresentation(BsonType.ObjectId)] // Ensures compatibility with MongoDB's ObjectId type
        public string MongoId { get; set; } = ObjectId.GenerateNewId().ToString();
        public int PlanetId { get; set; }
        public required Planet Planet { get; set; }
        public required double PositionX { get; set; }
        public required double PositionY { get; set; }
        public required double PositionZ { get; set; }
        public required double VelocityX { get; set; }
        public required double VelocityY { get; set; }
        public required double VelocityZ { get; set; }
        public required DateTime DateTime { get; set; }
        public required double JulianDate { get; set; }

        public static EphemerisPlanet convertEphemerisDictToObject(Dictionary<string, object> ephemerisDict, Planet planet)
        {
            return new EphemerisPlanet 
            {
                Planet = planet,
                PositionX = Convert.ToDouble(ephemerisDict["positionX"]),
                PositionY = Convert.ToDouble(ephemerisDict["positionY"]),
                PositionZ = Convert.ToDouble(ephemerisDict["positionZ"]),
                VelocityX = Convert.ToDouble(ephemerisDict["velocityX"]),
                VelocityY = Convert.ToDouble(ephemerisDict["velocityY"]),
                VelocityZ = Convert.ToDouble(ephemerisDict["velocityZ"]),
                DateTime = (DateTime) ephemerisDict["dateTime"],
                JulianDate = Convert.ToDouble(ephemerisDict["julianDate"])
            };
        }
    }

}
